version: 2.1
orbs:
  docker: circleci/docker@2.1.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: docker build
          command: |
            export TAG=$([ "${$CIRCLE_BRANCH}" == "master" ] && echo "latest" || echo "${$CIRCLE_BRANCH}")
            docker build -t os161:$TAG .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            sdocker push os161:$TAG

workflows:
  commit:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master