version: 2.1
orbs:
  docker: circleci/docker@2.1.1
jobs:
  build-and-push:
    environment:
      IMAGE_NAME: ronenniv/os161
    executor: 
      name: docker/docker
      resource_class: xlarge
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: docker build
          command: |
            export TAG=$([ "${CIRCLE_BRANCH}" == "master" ] && echo "latest" || echo "${CIRCLE_BRANCH}")
            docker build -t ${IMAGE_NAME}:${TAG} .
            docker push ${IMAGE_NAME}:${TAG}

workflows:
  commit:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master